name: flutter_ivn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  get_it: ^8.0.3
  injectable: ^2.5.0
  dio: ^5.7.0
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  dartz: ^0.10.1
  auto_route: ^9.2.2
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true